name: uygulama_odevi
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.5
  tflite_v2: ^1.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    #yapay zeka için model
    #kemik için
    - assets\data\bone_tflite\bone_tflite_labels.txt
    - assets\data\bone_tflite\bone_tflite_model_unquant.tflite

    #beyin için
    - assets\data\brain_converted_tflite\brain_labels.txt
    - assets\data\brain_converted_tflite\brain_model_unquant.tflite

    #image
    - assets\login\1.png
    - assets\login\2.png
    - assets\login\3.png
